# Generated by Django 5.2 on 2025-05-14 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_assignment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sql_dump', models.FileField(upload_to='teacher_dumps/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_databases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]