# Generated by Django 5.2 on 2025-05-19 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=100, unique=True)),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_instances', to='api.teacherdatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_databases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
