# Generated by Django 5.2.1 on 2025-05-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_assignment_standard_db_dump_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarydatabase',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
