# Generated by Django 5.2.1 on 2025-05-23 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_temporarydatabase_last_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacherdatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sql_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
