# Generated by Django 5.2.1 on 2025-05-26 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sqlhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='schema_script',
            field=models.TextField(help_text='SQL для ініціалізації бази даних'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='solution_hash',
            field=models.CharField(help_text="Хеш еталонного розв'язку", max_length=64),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='standard_solution',
            field=models.TextField(blank=True, help_text="SQL-розв'язок від вчителя", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Біографія або опис користувача', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Адміністратор'), ('TEACHER', 'Вчитель'), ('STUDENT', 'Студент')], default='STUDENT', max_length=10),
        ),
    ]
