# Generated by Django 5.2.1 on 2025-05-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_task_course_alter_assignment_schema_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
