# Generated by Django 5.2.1 on 2025-05-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_teacherdatabase_sql_dump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='etalon_db',
            field=models.FileField(blank=True, null=True, upload_to='teacher_dumps/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='original_db',
            field=models.FileField(upload_to='teacher_dumps/'),
        ),
    ]
