# Generated by Django 5.2.1 on 2025-05-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_task_etalon_db_alter_task_original_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarydatabase',
            name='teacher_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_instances', to='api.teacherdatabase'),
        ),
    ]
